<?php if (__FILE__ == $_SERVER['SCRIPT_FILENAME']) exit('Doğrudan erişim mümkün değil.');

$config['routes'] = array(
	array(array('GET', 'OPTIONS'), '/live_chat', '\controllers\Index#index'),
	array(array('POST', 'OPTIONS'), '/contact_operators/', '\controllers\Index#contact_operators'),
	array(array('POST', 'OPTIONS'), '/start_chat', '\controllers\Index#start_chat'),
	array(array('POST', 'OPTIONS'), '/send_message', '\controllers\Index#send_message'),
	array(array('POST', 'OPTIONS'), '/send_email', '\controllers\Index#send_email'),
	array(array('POST', 'OPTIONS'), '/stop_chat', '\controllers\Index#stop_chat'),
	array(array('POST', 'OPTIONS'), '/typing', '\controllers\Index#typing'),
	array(array('POST', 'OPTIONS'), '/update', '\controllers\Index#update'),
	array(array('GET', 'OPTIONS'), '/get_token', '\controllers\Index#get_token'),	
	array('POST', '/admin/index/update', '\controllers\admin\Index#update'),
	array(array('GET', 'POST'), '/admin', '\controllers\admin\Login#index'),
	array(array('GET', 'POST'), '/admin/login', '\controllers\admin\Login#index'),
	array(array('GET', 'POST'), '/admin/login/reset_password', '\controllers\admin\Login#reset_password'),
	array('GET', '/admin/index', '\controllers\admin\Index#index'),
	array('POST', '/admin/index/update_status', '\controllers\admin\Index#update_status'),
	array('POST', '/admin/index/get_online_departments', '\controllers\admin\Index#get_online_departments'),
	array('POST', '/admin/index/typing', '\controllers\admin\Index#typing'),
	array('POST', '/admin/index/send_message', '\controllers\admin\Index#send_message'),
	array('POST', '/admin/index/transfer_chat', '\controllers\admin\Index#transfer_chat'),
	array('POST', '/admin/index/start_chat', '\controllers\admin\Index#start_chat'),
	array('POST', '/admin/index/stop_chat', '\controllers\admin\Index#stop_chat'),
	array('POST', '/admin/index/watch_chat', '\controllers\admin\Index#watch_chat'),
	array('POST', '/admin/index/send_invitation', '\controllers\admin\Index#send_invitation'),
	array(array('GET', 'POST'), '/admin/profile', '\controllers\admin\Profile#index'),
	array('GET', '/admin/profile/delete_image', '\controllers\admin\Profile#delete_image'),
	array('GET', '/admin/logout', '\controllers\admin\Logout#index'),
	array(array('GET', 'POST'), '/admin/chat_history', '\controllers\admin\Chat_history#index'),
	array(array('GET', 'POST'), '/admin/chat_history/page/(:num)', '\controllers\admin\Chat_history#page'),
	array('GET', '/admin/chat_history/view_chat/(:num)', '\controllers\admin\Chat_history#view_chat'),
	array('POST', '/admin/chat_history/delete', '\controllers\admin\Chat_history#delete'),
	array(array('GET', 'POST'), '/admin/canned_messages', '\controllers\admin\Canned_messages#index'),
	array(array('GET', 'POST'), '/admin/canned_messages/page/(:num)', '\controllers\admin\Canned_messages#page'),
	array(array('GET', 'POST'), '/admin/canned_messages/edit/(:num)', '\controllers\admin\Canned_messages#edit'),
	array('POST', '/admin/canned_messages/delete', '\controllers\admin\Canned_messages#delete'),
	array('GET', '/admin/departments', '\controllers\admin\Departments#index'),
	array('GET', '/admin/departments/page/(:num)', '\controllers\admin\Departments#page'),
	array(array('GET', 'POST'), '/admin/departments/add', '\controllers\admin\Departments#add'),
	array(array('GET', 'POST'), '/admin/departments/edit/(:num)', '\controllers\admin\Departments#edit'),
	array('POST', '/admin/departments/delete', '\controllers\admin\Departments#delete'),
	array('GET', '/admin/operators', '\controllers\admin\Operators#index'),
	array('GET', '/admin/operators/page/(:num)', '\controllers\admin\Operators#page'),
	array(array('GET', 'POST'), '/admin/operators/add', '\controllers\admin\Operators#add'),
	array(array('GET', 'POST'), '/admin/operators/edit/(:num)', '\controllers\admin\Operators#edit'),
	array('POST', '/admin/operators/delete', '\controllers\admin\Operators#delete'),
	array('GET', '/admin/groups', '\controllers\admin\Groups#index'),
	array('GET', '/admin/groups/page/(:num)', '\controllers\admin\Groups#page'),
	array(array('GET', 'POST'), '/admin/groups/add', '\controllers\admin\Groups#add'),
	array(array('GET', 'POST'), '/admin/groups/edit/(:num)', '\controllers\admin\Groups#edit'),
	array('POST', '/admin/groups/delete', '\controllers\admin\Groups#delete'),
	array('GET', '/admin/blocked_visitors', '\controllers\admin\Blocked_visitors#index'),
	array('GET', '/admin/blocked_visitors/page/(:num)', '\controllers\admin\Blocked_visitors#page'),
	array(array('GET', 'POST'), '/admin/blocked_visitors/add', '\controllers\admin\Blocked_visitors#add'),
	array(array('GET', 'POST'), '/admin/blocked_visitors/add/(:any)', '\controllers\admin\Blocked_visitors#add'),
	array('POST', '/admin/blocked_visitors/delete', '\controllers\admin\Blocked_visitors#delete'),
	array('GET', '/admin/access_logs', '\controllers\admin\Access_logs#index'),
	array('GET', '/admin/access_logs/page/(:num)', '\controllers\admin\Access_logs#page'),
	array(array('GET', 'POST'), '/admin/settings', '\controllers\admin\Settings#index')
);

?>
